name: Nuxt Web App CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"
      # Pick your own package manager and build script
      - run: npm install
      - run: npm run postinstall
      - run: npx prisma generate
      - run: npx nuxt build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./.output

      - name: Push build to branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: build
          publish_dir: ./.output
          force_orphan: true