name: Deploy to server

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Install grunt
      run: npm install grunt --save-dev
    - name: Build application
      run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Install grunt-ftp-deploy
      run: npm install grunt-ftp-deploy --save-dev
    - name: Deploy to server
      run: grunt ftp-deploy
