name: Deploy to server

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install vinyl-ftp
      run: npm install vinyl-ftp
    - name: Deploy to server
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        export VinylFtp=$(require 'vinyl-ftp')
        ftp = new VinylFtp({
          host: process.env.FTP_HOST,
          user: process.env.FTP_USERNAME,
          password: process.env.FTP_PASSWORD,
          parallel: 10,
          log: console.log
        });
        globs = ['.output/**/*'];
        return ftp.src(globs, { base: '.output', buffer: false })
          .pipe(ftp.dest('/public_html/nuxt'));
