name: Deploy to server

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Build application
      run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Install grunt and grunt-ftp-deploy
      run: npm install -g grunt grunt-ftp-deploy
    - name: Deploy to server
      run: grunt ftp-deploy --auth.host='${{ secrets.FTP_HOST }}' --auth.port=21 --auth.authKey='${{ secrets.FTP_AUTH_KEY }}' --src='dist' --dest='/public_html/nuxt'
