name: Deploy to server

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Build application
      run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Install FTP-KR
      run: npm install ftp-kr
    - name: Deploy to server
      run: node -e "require('ftp-kr').deploy({ host: '${{ secrets.FTP_HOST }}', user: '${{ secrets.FTP_USERNAME }}', password: '${{ secrets.FTP_PASSWORD }}', localPath: '.output', remotePath: '/public_html/nuxt' })"
